version: '3'
services:
  nginx-proxy:
    image: nginx:1.17.6-alpine
    ports:
      - '127.0.0.1:9083:9083'
    environment:
      - ACCESS_CONTROL_ALLOW_ORIGIN=http://localhost:9082
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx_envsubst.conf.template:/var/lib/hypothesis/nginx_envsubst.conf.template
    command: bin/sh -c "envsubst '$${ACCESS_CONTROL_ALLOW_ORIGIN}' < /var/lib/hypothesis/nginx_envsubst.conf.template > /var/lib/hypothesis/nginx_envsubst.conf && exec nginx"

